name: PUSH EVENT
on: [push, pull_request]

jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: reviewer run
        uses: birariro/chicken-reviewer
        with:
          github-token: ${{ secrets.GIT_TOKEN }}

